### ISSUE TITLE
windows下Postgresql 9.x竟然也能支持zhparser中文分词哦！但还是遇到一个问题没解决

### ISSUE THREAD

**Issue by kerneltravel** [amutu/zhparser#10]
fork和改进了Windows下编译zhparser。在这里描述了遇到的一个问题
https://github.com/kerneltravel/zhparser#windows-%E6%94%AF%E6%8C%81

这个问题超出我目前掌握的，不知道怎么找线索了。求助

**Comment by wjw0716** [comment]
@kerneltravel  您好，请问您解决这个问题了吗？

**Comment by kerneltravel** [comment]
@wjw0716  还没解决。

目前根据francs3的文档 执行：

ALTER TEXT SEARCH CONFIGURATION chinesefts ADD MAPPING FOR  n,v,a,i,e,l WITH simple; 
的时候，windows下运行的pgsql 9.5.2服务主动断开连接了。原因未知。希望有人能继续解决这个问题！！

**Comment by zlianzhuang** [comment]
16年的了。先关闭了。
