### ISSUE TITLE
./check.sh

### ISSUE THREAD

**Issue by willycode** [amutu/zhparser#12]
1a2

> psql:sql/zhparser.sql:1: ERROR:  could not access file "$libdir/zhparser": No such file or directory
> 3a5
> psql:sql/zhparser.sql:5: ERROR:  text search parser "zhparser" does not exist
> 4a7
> psql:sql/zhparser.sql:7: ERROR:  text search configuration "testzhcfg" does not exist
> 7,81c10

**Comment by iykon** [comment]
I have the same error too: could not access file "$libdir/zhparser": No such file or directory.

**Comment by amutu** [comment]
fixed by 24144a1308a8f236380fb55523980d843a7cf1eb
thank！
