### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by lichao060103** [amutu/zhparser#14]
Makefile:17: /usr/pgsql-9.5/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
gmake: **\* No rule to make target `/usr/pgsql-9.5/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.

**Comment by amutu** [comment]
缺少/usr/pgsql-9.5/lib/pgxs/src/makefiles/pgxs.mk，请问你的PG是如何安装的？可以尝试自己编译PG

**Comment by Bruce-zxy** [comment]
我的是PostgreSQL 10.8，我也遇到了同样的问题，我是在PostgreSQL官网按提示的步骤完成的安装。
![image](https://user-images.githubusercontent.com/22904758/58449858-f632f180-813e-11e9-8590-f63215f534f3.png)

但是我通过安装postgresql10-devel.x86_64的包就能够编译通过了

![image](https://user-images.githubusercontent.com/22904758/58449810-de5b6d80-813e-11e9-9eb2-fa3bf34544ef.png)

![image](https://user-images.githubusercontent.com/22904758/58449908-2d090780-813f-11e9-90fa-c42c3c84bd5b.png)
