### ISSUE TITLE
创建扩展时出错

### ISSUE THREAD

**Issue by neilzhao123** [amutu/zhparser#15]
操作系统： ubuntu
PG版本：9.2
postgres=# create extension zhparser;
ERROR:  could not load library "/opt/PostgreSQL/9.2/lib/postgresql/zhparser.so": /opt/Post
greSQL/9.2/lib/postgresql/zhparser.so: undefined symbol: palloc

**Comment by amutu** [comment]
你是如何安装的？
能否提供重现步骤？
