### ISSUE TITLE
Please give a chance to  to use a specific pg_config while in compiling

### ISSUE THREAD

**Issue by KDr2** [amutu/zhparser#17]
This is a trivial change so I didn't fork the repo to file a PR for such a little update, I just paste the patch here.

The patch: http://paste.debian.net/plainh/6a9f193f

Please consider applying it by:
```
curl http://paste.debian.net/plainh/6a9f193f -o xxx.patch
git am xxx.patch
```
Thanks.

**Comment by KDr2** [comment]
[0001-give-a-chance-to-use-a-specific-pg_config-in-compili.patch.txt](https://github.com/amutu/zhparser/files/674968/0001-give-a-chance-to-use-a-specific-pg_config-in-compili.patch.txt)

Patch atteched.

**Comment by amutu** [comment]
done by c7356e06f2f8faa7eb7d6e1c7f451fcb0ed2cc29
thanks！
