### ISSUE TITLE
How to exclude dot from separators?

### ISSUE THREAD

**Issue by ArturFormella** [amutu/zhparser#18]
Hello!
How to exclude dot and % sign from separators?
`SELECT token FROM ts_parse('testzhcfg', '肖特基整流 99.02.7%060.98')`
```
token
肖特基
整流
99
.
02
.
7
%
060.98
```
Expected:
```
token
肖特基
整流
99.02.7%060.98
```
Thank you.

**Comment by amutu** [comment]
Do not support this because scws make the segment and zhparser can not control its behaviour.
But you can reconstruct the “99.02.7%060.98” or similar using the agg function of SQL.
