### ISSUE TITLE
冒昧的问一下，这个项目还在维护吗？打扰了。

### ISSUE THREAD

**Issue by sgon00** [amutu/zhparser#19]
最近打算使用postgresql进行中文搜索，搜到推荐最多的就是pg_jieba和zhparser。不过查看这两个github情况，都是一两年没更新过了。冒昧的问一下作者，停止维护的原因是什么？是否可以放心的在现有的项目里使用zhparser？如果这个项目不打算继续维护了，有什么好的替代方案？使用Elasticsearch吗？非常抱歉打扰您。非常感谢。

**Comment by amutu** [comment]
会继续维护
请问你遇到什么问题了？
