### ISSUE TITLE
does zhparser support postgresql 10.x？

### ISSUE THREAD

**Issue by gzliudan** [amutu/zhparser#20]
请问zhparser支持postgresql 10.x吗？

**Comment by amutu** [comment]
理论上9.2及以上版本都是支持的，你遇到什么问题了吗？

**Comment by gzliudan** [comment]
我还没碰到问题，打算用postgresql 10，怕中文全文检索碰到问题。请问自定义词典的格式是怎样的？

**Comment by amutu** [comment]
自定义词典格式文档有描述：https://github.com/amutu/zhparser/blob/master/README.md

**Comment by gzliudan** [comment]
2个自定义的词库，单个词库都是几十万个词，词库之间有少量重复，性能没问题吧？
