### ISSUE TITLE
出现了特定文字不能to_tsvector分词的情况

### ISSUE THREAD

**Issue by liyibo1110** [amutu/zhparser#28]
[SQL]select to_tsvector('chinese'::regconfig, '自从用了液体，别的再也用不了了，太好用，毫无感觉，超级好用，大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱大爱')

[Err] ERROR:  invalid byte sequence for encoding "UTF8": 0xe5 0xa4

这种连续2个字不断重复的内容，都会报这类错误，导致GIN索引不能建立。（chinese就是例子上的testzhcfg）

**Comment by liyibo1110** [comment]
版本应该是0.1.4

**Comment by zlianzhuang** [comment]
用新版本看看吧。
