### ISSUE TITLE
centos 7.4/7.5+postgresql 11 环境make报错，什么时候支持postgres11呀？

### ISSUE THREAD

**Issue by zyd** [amutu/zhparser#29]

**Comment by mofei031026** [comment]
同问

**Comment by amutu** [comment]
报错信息提供一下？

**Comment by zyd** [comment]
/opt/rh/llvm-toolset-7/root/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I/usr/local/include/scws  -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o zhparser.bc zhparser.c
make: /opt/rh/llvm-toolset-7/root/usr/bin/clang: Command not found
make: *** [zhparser.bc] Error 127

**Comment by zlianzhuang** [comment]
clang: Command not found  安装这个命令就可以了。

**Comment by zyd** [comment]
yum install clang之后重新make，还是报错
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -I/usr/local/include/scws  -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o zhparser.o zhparser.c
zhparser.c: In function ‘init’:
zhparser.c:223:6: warning: implicit declaration of function ‘SplitIdentifierString’ [-Wimplicit-function-declaration]
      if(!SplitIdentifierString(extra_dicts,',',&elemlist)){
      ^
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -shared -o zhparser.so zhparser.o -L/usr/pgsql-11/lib  -Wl,--as-needed -L/usr/lib64/llvm5.0/lib  -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/pgsql-11/lib',--enable-new-dtags  -lscws -L/usr/local/lib -Wl,-rpath -Wl,/usr/local/lib 
/opt/rh/llvm-toolset-7/root/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I/usr/local/include/scws  -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o zhparser.bc zhparser.c
make: /opt/rh/llvm-toolset-7/root/usr/bin/clang: Command not found
make: *** [zhparser.bc] Error 127
