### ISSUE TITLE
编译安装后，不能导入

### ISSUE THREAD

**Issue by longfeij** [amutu/zhparser#34]
#./bin/gd_config --libdir
/home/greatdbdata/greatdb_p/lib

#ll /home/greatdbdata/greatdb_p/lib/zhparser.so
/home/greatdbdata/greatdb_p/lib/zhparser.so

#/home/greatdbdata/greatdb_p/bin/psql  -Ubenchmarksql -p5432 -h127.0.0.1 -d great_db
psql (11.4)
Type "help" for help.

great_db=# CREATE EXTENSION zhparser;
ERROR:  could not access file "$libdir/zhparser": 没有那个文件或目录
great_db=# CREATE EXTENSION zhparser;
ERROR:  could not access file "$libdir/zhparser": 没有那个文件或目录
great_db=# exit

**Comment by zlianzhuang** [comment]
通常都不会有这样的问题，这个应该是由于环境导致的，得登录你的机器才能知道具体原因。

**Comment by CN-Eden** [comment]
你可以先查下你的postgresql版本  拓展文件目录默认位置，再把zhparser.control放到这个目录下面，再试试
