### ISSUE TITLE
How to support version 11?

### ISSUE THREAD

**Issue by zhuliangcai** [amutu/zhparser#35]
test=# create extension zhparser ;
ERROR:  incompatible library "/usr/pgsql-11/lib/zhparser.so": version mismatch
DETAIL:  Server is version 11, library is version 9.2.

**Comment by Vivi1838** [comment]
I have this issue too, please...I need this extension for pg11...

**Comment by zlianzhuang** [comment]
zhparser support version 11 now.  if you have two version of pg on your machine?  could you  open teamview?  i can connet teamview and repair it for you.   my email: zlianzhuang@163.com.

zhparser 现在支持11版本，你的机器上是否装了两个版本的pg。你能开teamview的话，我可以连接你的机器帮助你解决下，我的邮件是zlianzhuang@163.com.

**Comment by Vivi1838** [comment]
Thank you very much , I have solved this problem ,I find that postgresql and postgresql-11 were both on my machine, and i didn`t add my pg11 to my PATH, so I uninstalled the postgresql (9.2) and fixed my PATH, and installed scws and zhparser again, it worked ! Thanks again.
非常感谢，我已经解决了，发现机器上是有两个版本的pg，而且没有pg11的环境变量，把9.2的卸载了，然后加上pg11的环境变量之后，我重新安装了scws和zhparser，成功了！再次感谢。

**Comment by zlianzhuang** [comment]
没事

**Comment by yijuanmao** [comment]
您好我现在也是这个问题，请问怎么解决啊

**Comment by zlianzhuang** [comment]
把原来的版本删除了。确保你的环境用的都是11版本的内容。然后在重新编译就可以了

**Comment by yijuanmao** [comment]
您好！您这边有彻底删除postgres操作步骤吗？我这边国内网站很少有有卸载的资料!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhangLianZhuang"<notifications@github.com&gt;; 
发送时间: 2020年1月2日(星期四) 中午12:19
收件人: "amutu/zhparser"<zhparser@noreply.github.com&gt;; 
抄送: "牛奶喝不到纯牛奶"<824414828@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [amutu/zhparser] How to support version 11? (#35)




把原来的版本删除了。确保你的环境用的都是11版本的内容。然后在重新编译就可以了

**Comment by zlianzhuang** [comment]
如果你用了包删除命令，去删除的话，但是仍然有剩余文件存在。可以用locate命令 查找下你的文件的安装路径，然后给删除了就行了。

**Comment by yijuanmao** [comment]
好的，我先试试，谢谢拉




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhangLianZhuang"<notifications@github.com&gt;; 
发送时间: 2020年1月3日(星期五) 中午1:00
收件人: "amutu/zhparser"<zhparser@noreply.github.com&gt;; 
抄送: "牛奶喝不到纯牛奶"<824414828@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [amutu/zhparser] How to support version 11? (#35)




如果你用了包删除命令，去删除的话，但是仍然有剩余文件存在。可以用locate命令 查找下你的文件的安装路径，然后给删除了就行了。
