### ISSUE TITLE
can't update to 2.1 version

### ISSUE THREAD

**Issue by zhangyonguu** [amutu/zhparser#37]
Hi there: 

I have zhparser of version 1.0, and I exec the command in psql:  `alter extension zhparser update`,  but I only get the NOTICE: `NOTICE:  version "1.0" of extension "zhparser" is already installed`. 

How can I upgrade to version 2.1?

**Comment by zlianzhuang** [comment]
得先下载，安装2.1的库后。在执行 alter update
