### ISSUE TITLE
添加字典不起作用

### ISSUE THREAD

**Issue by f-cg** [amutu/zhparser#38]
postgres12，zhparser2.1 拿dict_extra.txt作例子，放到tsearch_data目录和base/数据库ID下都不管用。

**Comment by ktwc37** [comment]
我的环境是postgresql11, 也遇到了同样问题，不知道为什么自定义词典不起作用，但使用scws命令行是可以的。

**Comment by ktwc37** [comment]
也已经配置了zhparse.extra_dicts

**Comment by zlianzhuang** [comment]
zhparse.extra_dicts='xx.txt'
PGDATA/share/tsearch_data/xx.txt 

通常只需要这个配置下就可以了.
2.1的自定义词库是放到 ${PGDATA}/base/${DBID}/zhprs_dict_${DBNAME}.txt",

PGDATA/DBID/DBNAME 替换成自己实际环境的

**Comment by zlianzhuang** [comment]
每次更新字典后,需要断开连接,新的连接才可以.
