### ISSUE TITLE
无法为postgresql-12编译版本

### ISSUE THREAD

**Issue by forestlzj** [amutu/zhparser#39]
在centos, export PG_CONFIG=/usr/pgsql-12/bin/pg_config
然后执行
make && make install
报错。
Makefile:20: /usr/pgsql-12/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target `/usr/pgsql-12/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.

**Comment by zlianzhuang** [comment]
locate  pgxs.mk  或是 find  / -name pgxs.mk  能找到么

**Comment by forestlzj** [comment]
没有找到，已经安装postgresql12-devel

**Comment by baiyideheimodao** [comment]
我也遇到了这样的问题 
incompatible library "/usr/local/pgsql/lib/zhparser.so": version mismatch
Server is version 12, library is version 11.

**Comment by wangjunjx8868** [comment]
我终于解决了，遇到这个问题 要进行三步
1.安装 llvm-toolset-7-clang >= 4.0.1
2.安装 llvm5.0-devel >= 5.0

然后再安装
3. yum install postgresql12-devel -y
4. export PG_CONFIG=/usr/pgsql-12/bin/pg_config
5. make && make install
就可以了
