### ISSUE TITLE
Error: SSL SYSCALL error: EOF detected

### ISSUE THREAD

**Issue by dreamsxin** [amutu/zhparser#4]
当执行了
```sql
-- make test configuration using parser

CREATE TEXT SEARCH CONFIGURATION testzhcfg (PARSER = zhparser);

-- add token mapping

ALTER TEXT SEARCH CONFIGURATION testzhcfg ADD MAPPING FOR n,v,a,i,e,l WITH simple;
```
之后，使用pgadmin重连数据库，点击相应schema都会出现这个错误。

**Comment by jesonyang001** [comment]
我也有同樣問題。並執行select ts_token_type('zhparser');也會出錯。ssl syscall error: eof detected the connection to the server was lost. attempting reset: failed.

**Comment by dreamsxin** [comment]
@jesonyang001 暂时使用我这个分支补丁
https://github.com/amutu/zhparser/pull/5
https://github.com/dreamsxin/zhparser

**Comment by jesonyang001** [comment]
非常感謝，已經解決。另外想請問下如何處理繁體中文分詞？需要增加自定義繁體字典嗎？還是zhparser或者SCWS本身有設置選項？謝謝！

**Comment by dreamsxin** [comment]
@jesonyang001 SCWS官网有繁体字典，不过繁体的字典字不多，你也可以把简体的字典转为繁体，或者自己制作字典。

**Comment by jesonyang001** [comment]
繁體字典確實有些詞不能分，詞較少，先用著。謝謝！

**Comment by amutu** [comment]
已经merge了上面的patch，谢谢！
