### ISSUE TITLE
自定义词库后 ts_parse 是起作用的，to_tsquery 不起作用

### ISSUE THREAD

**Issue by fanybook** [amutu/zhparser#40]

**Comment by bosimao1988512** [comment]
向EXT SEARCH CONFIGURATION添加词性 x

**Comment by bosimao1988512** [comment]
向 TEXT SEARCH CONFIGURATION添加词性 x

**Comment by zlianzhuang** [comment]
也可以断开连接,再次连接一下看看.

**Comment by ccfish86** [comment]
实测`ALTER TEXT SEARCH CONFIGURATION cnzhcfg ADD MAPPING FOR x WITH simple;`就好了，也不用重启/重连。
![image](https://user-images.githubusercontent.com/15622514/143675297-19f6728e-1572-4c77-a8dd-ddb809f37d3c.png)

**Comment by yoko-murasame** [comment]
> 

Like this: `ALTER TEXT SEARCH CONFIGURATION [yourCfg] ADD MAPPING FOR x WITH simple;`
