### ISSUE TITLE
create extension zhparser在有表空间的情况下失败

### ISSUE THREAD

**Issue by iveteran** [amutu/zhparser#41]
localhost fimatrix@cnstock=# create extension zhparser;
ERROR:  could not open file "/home/postgres/12/data/base/35282/zhprs_dict_cnstock.txt" for writing: No such file or directory
HINT:  COPY TO instructs the PostgreSQL server process to write a file. You may want a client-side facility such as psql's \copy.
CONTEXT:  SQL statement "copy (select word, tf, idf, attr from zhparser.zhprs_custom_word) to '/home/postgres/12/data/base/35282/zhprs_dict_cnstock.txt' encoding 'utf8'"
PL/pgSQL function sync_zhprs_custom_word() line 17 at EXECUTE
在使用了表空间的情况有这个问题，我的数据库环境如：
localhost fimatrix@cnstock=# \l+
                                                                      List of databases
    Name     |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges   |  Size   |   Tablespace    |                Description
-------------+----------+----------+------------+------------+-----------------------+---------+-----------------+--------------------------------------------
 cnstock     | fimatrix | UTF8     | en_US.utf8 | en_US.utf8 |                       | 581 MB  | tblspc_cnstock  |
 cnstock_old | fimatrix | UTF8     | en_US.utf8 | en_US.utf8 |                       | 443 MB  | tblspc_cnstock  |
 fimatrix    | fimatrix | UTF8     | en_US.utf8 | en_US.utf8 |                       | 12 MB   | tblspc_fimatrix |
 postgres    | postgres | UTF8     | en_US.utf8 | en_US.utf8 |                       | 8025 kB | pg_default      | default administrative connection database
 template0   | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +| 7825 kB | pg_default      | unmodifiable empty database
             |          |          |            |            | postgres=CTc/postgres |         |                 |
 template1   | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +| 7825 kB | pg_default      | default template for new databases
             |          |          |            |            | postgres=CTc/postgres |         |                 |
(6 rows)

localhost fimatrix@cnstock=#
localhost fimatrix@cnstock=# \db                                                                                                                                                            List of tablespaces
      Name       |  Owner   |                   Location
-----------------+----------+-----------------------------------------------
 pg_default      | postgres |
 pg_global       | postgres |
 tblspc_cnstock  | fimatrix | /home/postgres/12/tablespaces/tblspc_cnstock
 tblspc_fimatrix | fimatrix | /home/postgres/12/tablespaces/tblspc_fimatrix
(4 rows)

localhost fimatrix@cnstock=# select current_database();                                                                                                          current_database
------------------
 cnstock
(1 row)

[postgres@dev ~]$ ll 12/tablespaces/tblspc_cnstock/PG_12_201909212/
total 68
drwx------. 2 postgres postgres 12288 Jun  7 17:10 16389
drwx------. 2 postgres postgres 24576 Jun 26 22:21 35282
drwx------. 2 postgres postgres     6 May 30 15:28 pgsql_tmp

**Comment by iveteran** [comment]
` 45                                                                                                                                                              46   select data_dir || '/base/' || database_oid || '/zhprs_dict_' || current_database() || '.txt' into dict_path;                                              47   select data_dir || '/base/' || database_oid || '/zhprs_dict_' || current_database() || '.tag' into time_tag_path;                                          48                                                                                                                                                              49   query = 'copy (select word, tf, idf, attr from zhparser.zhprs_custom_word) to ' || chr(39) || dict_path || chr(39) || ' encoding ' || chr(39) || 'utf8'       || chr(39) ;                                                                                                                                                 50   execute query;`

**Comment by iveteran** [comment]
我的解决方法：拷贝的目标文件文件名已经包含了数据库名，就可以不要在文件路径包含数据库oid，补丁文件见附件。
[zhparser_with_tablespace.patch.txt](https://github.com/amutu/zhparser/files/4837597/zhparser_with_tablespace.patch.txt)

**Comment by zlianzhuang** [comment]
已经更新,2.2版本.alter extension zhparser update TO "2.2";

**Comment by weiya1990** [comment]
> 我的解决方法：复制附件的目标文件名已经包含了数据库名，就可以不要在文件路径包含数据库类，下载文件见。 [zhparser_with_tablespace.patch.txt](https://github.com/amutu/zhparser/files/4837597/zhparser_with_tablespace.patch.txt)

请问[zhparser_with_tablespace.patch.txt](https://github.com/amutu/zhparser/files/4837597/zhparser_with_tablespace.patch.txt)这个文件是放到那个地方，需要重新编译吗？可以说的详细点吗？
