### ISSUE TITLE
自定义词库 to_tsquery  to_tsvector    自定义词都会丢掉

### ISSUE THREAD

**Issue by mago-git** [amutu/zhparser#42]
自定义词库 2.1  遇到个问题，不知道如何解决 to_tsvector   to_tsquery  自定义词都会丢掉，只有ts_parse 是正常的
例如 定义“石业”这个词
```
select ts_parse('zhparser','金时石业');
(110,金时)
(120,石业)
```
SELECT   to_tsquery('zhcfg', '金时石业');
'金时'

**Comment by manortec** [comment]
词性120是 特殊词 词性，你需要在你的配置里添把特殊词对应的词性标志 x 添加上去，用以下命令：

ALTER TEXT SEARCH CONFIGURATION your_cfg_name ADD MAPPING FOR x WITH simple;

把 your_cfg_name 替换成你的配置名称
