### ISSUE TITLE
无法为postgresql-13编译版本

### ISSUE THREAD

**Issue by brightgems** [amutu/zhparser#47]
export PG_CONFIG=/usr/lib/postgresql/13/bin/pg_config
make & make install

错误如下:
```
r.o zhparser.c
zhparser.c:10:10: fatal error: postgres.h: No such file or directory
 #include "postgres.h"
          ^~~~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'zhparser.o' failed
```

**Comment by brightgems** [comment]
已经解决, 需要安装 postgresql-server-dev-13
```
sudo apt install postgresql-server-dev-13
```

**Comment by wangjunjx8868** [comment]
> 已经解决, 需要安装 postgresql-server-dev-13
> 
> ```
> sudo apt install postgresql-server-dev-13
> ```

Centos 无法安装postgresql-server-dev-11
我知道用 yum 不是 sudo apt

**Comment by zlianzhuang** [comment]
把dev安装好就差不多了.
