### ISSUE TITLE
执行 select sync_zhprs_custom_word() 时失败

### ISSUE THREAD

**Issue by manortec** [amutu/zhparser#48]
在使用 执行函数(     select sync_zhprs_custom_word()   )同步自定义词库时，出现了以下错误。不知道是何原因，由于使用了云端数据库，没权限进行源码或词库文本文件打补丁之类的操作，请帮我看看有什么解决办法，十分感谢！

 2021年1月18日 19:24:49
	
STATEMENT: /* Query from DMS-WEBSQL-0-Qid_1610969088976 by user 1943298325287307 */ select sync_zhprs_custom_word()
2021年1月18日 19:24:49
	
CONTEXT: PL/pgSQL function sync_zhprs_custom_word() line 17 at EXECUTE
2021年1月18日 19:24:49
	
ERROR: 22004: query string argument of EXECUTE is null

**Comment by favoyang** [comment]
如果您使用的是阿里云PG12，PG13（对应的zhparser 2.1）。那么只能等待阿里云修复该产品的缺陷。在本文书写时2021-02-23，他们的云数据库有一个自定义词库文件的权限问题，因此无法同步到文件中。

```
db-test=> select to_tsvector('zh-profile','计算机');
NOTICE:  zhparser add dict : "/u01/pgsql/share/tsearch_data/dict_extra.xdb" failed!

db-test=> select sync_zhprs_custom_word();
ERROR:  query string argument of EXECUTE is null
CONTEXT:  PL/pgSQL function sync_zhprs_custom_word() line 17 at EXECUTE
```

具体修复时间，据推测是2021年3月以后。您可以选择等待或暂时使用PG11。阿里云PG11可以支持zhparser1.0的自定义词库的更新函数，并可以正常使用。https://help.aliyun.com/document_detail/140894.html?spm=5176.smartservice_service_chat.0.0.1069709aIN5R1g

**Comment by zlianzhuang** [comment]
使用超级用户执行就可以了.
