### ISSUE TITLE
能否支持docker？

### ISSUE THREAD

**Issue by xsq0718** [amutu/zhparser#53]
我pg使用docker运行的，能否在容器内安装zhparser？

**Comment by abcfy2** [comment]
我维护了一个docker镜像，欢迎测试： https://hub.docker.com/repository/docker/abcfy2/zhparser

**Comment by xsq0718** [comment]
感谢

**Comment by wangjunjx8868** [comment]
> 我维护了一个docker镜像，欢迎测试： https://hub.docker.com/repository/docker/abcfy2/zhparser

自定义词典zhparser.zhprs_custom_word 不生效怎么？重启dcoker也不行
