### ISSUE TITLE
CentOS 7 安装提示ERROR:  extension "zhparser" has no installation script nor update path for version "2.1"

### ISSUE THREAD

**Issue by CN-Eden** [amutu/zhparser#55]
CentOS 7 安装提示ERROR:  extension "zhparser" has no installation script nor update path for version "2.1"，请问怎么解决

**Comment by zlianzhuang** [comment]
你是通过代码编译的么? 看看目录下是否包含了zhparser--1.0--2.0.sql
zhparser--1.0.sql
zhparser--2.0--2.1.sql
zhparser--2.0.sql
zhparser--2.1.sql  这些文件.

**Comment by zlianzhuang** [comment]
看看你pg的pg 安装目录下/share/extension 中是否有那些文件
