### ISSUE TITLE
ERROR:  incompatible library "/usr/pgsql-9.6/lib/zhparser.so": version mismatch DETAIL:  Server is version 9.6, library is version 9.2.

### ISSUE THREAD

**Issue by CN-Eden** [amutu/zhparser#56]
ERROR:  incompatible library "/usr/pgsql-9.6/lib/zhparser.so": version mismatch
DETAIL:  Server is version 9.6, library is version 9.2.

请问怎么解决

**Comment by zlianzhuang** [comment]
这种多少环境安装了多套PG的问题. 你可以  make PG_CONFIG=/usr/lib/postgresql/9.5/bin/pg_config 指定你所需要的版本.
