### ISSUE TITLE
自定义词库 2.1 该如何备份，然后在另一个主机上恢复？

### ISSUE THREAD

**Issue by zw963** [amutu/zhparser#61]
我之前加了不少自定义关键字，但是后来换了一个服务器，我使用 postgres 的 dumpall 备份了数据库，但是我发现，自定义词库并未导入，请问，我该备份并稍后恢复那个文件呢？又或者其他办法？

**Comment by amutu** [comment]
看这里：https://github.com/amutu/zhparser/blob/master/zhparser--2.1.sql#L46
可以拷贝这个文件

**Comment by zlianzhuang** [comment]
从备份还原后，自定义词库的内容仅存储在表中，还没一落盘，可以像amutu那样拷贝下，或是使用 sync_zhprs_custom_word 刷新下也可以。
