### ISSUE TITLE
Inexistant default version ?

### ISSUE THREAD

**Issue by catuss-a** [amutu/zhparser#64]
`https://github.com/amutu/zhparser/blob/master/zhparser.control`

Shows default version 2.2 however there is no `zhparser--2.2.sql`

I had the issue without providing an extension version when creating it such as :

`CREATE EXTENSION zhparser;` however ` CREATE EXTENSION zhparser VERSION '2.1';` fixed it

Postgres version 9.6

(Postgres 13+ worked fine without specifying the version)

**Comment by zlianzhuang** [comment]
http://citusdb.cn/?p=755

then install 2.2(default), the first sql is zhparser--2.1.sql, secend sql is zhparser--2.1--2.2.sql  (update 2.1->2.2).
