### ISSUE TITLE
编译错误：无pgxs路径

### ISSUE THREAD

**Issue by WShihan** [amutu/zhparser#73]
os: windows10
pg: 14.2.7

-----------------------------------------
使用cygwin编译，报如下错误：
![image](https://user-images.githubusercontent.com/52617949/233598445-66d52d6a-8216-4f09-a776-08918dae333d.png)

我尝试添加该缺失文件，了解到需要安装postgresql-server-devel，但是没有找到windows系统的安装方式，请问如何解决呢？或者有朋友能分享编译后的插件吗？不胜感激。

**Comment by zlianzhuang** [comment]
用linux版吧，windows 上的开发者比较少，
